### PR TITLE
Remove openocd

### PR DESCRIPTION
**Pull request by gcampbell-msft**

### CODE REVIEW

**Review by BillyONeal — COMMENTED** [review]
* Removing old versions from registries is generally not a thing because it breaks 'no changes means no changes'.
* Don't there need to be index.yaml changes?

**Comment by gcampbell-msft** [comment]
> * Removing old versions from registries is generally not a thing because it breaks 'no changes means no changes'.
> * Don't there need to be index.yaml changes?

Ah, yes, there do need to be index.yaml changes.

**Comment by rnicolas-manus** [comment]
If this is removed, how do I install OpenOCD using vcpkg? What will happen to the projects and teams already configured to use it?

**Comment by cinnamondev** [comment]
The deletion of repository microsoft/openocd has already brought this into effect (no sources available), unfortunately. 
Instead of removing openOCD entirely would it not be more beneficial to existing projects to use openocd-org/openocd going forward?

(also, microsoft:tools/raspberrypi/pico-sdk is still a dependent on openOCD (0.11.0-ms2), though it should not require it)

**Review by BillyONeal — APPROVED** [review]

**Comment by EaselinkBachmann** [comment]
This commit broke installation of `"microsoft:tools/ninja-build/ninja": "1.10.2"`. The index refers to ninja as index 17, but it actually has index 13. The indices of the `pico-sdk` package also need to be adjusted.

**Pull request merged**
